__all__ = [
    "KEY_INT", "KEY_FRC", "KEY_FLT",
    "KEY_CNS", "KEY_VAR",
    "KEY_ADD", "KEY_MUL", "KEY_POW",
    "KEY_FNC",
    "KEY_LIM", "KEY_DER", "KEY_ITG",

    "KEY_SET_INTVL",
    "KEY_SET_EMPTY", "KEY_SET_UNVSL",
    "KEY_SET_FINIT",
    "KEY_SET_UNION", "KEY_SET_INTSC",
    "KEY_SET_DFRNC", "KEY_SET_CMPLM",
    "KEY_SET_DOMAIN",

    "CONSTKEY_INF", "CONSTKEY_NEGINF", "CONSTKEY_UNDEF",

    "FUNC_ABS",
    "FUNC_SIN", "FUNC_COS", "FUNC_TAN",
    "FUNC_SEC", "FUNC_CSC", "FUNC_COT",
    "FUNC_ARCSIN", "FUNC_ARCCOS", "FUNC_ARCTAN",
    "FUNC_ARCSEC", "FUNC_ARCCSC", "FUNC_ARCCOT",
    "FUNC_LN", "FUNC_LOG",

    "DOMAIN_NATURAL",
    "DOMAIN_INTEGER",
    "DOMAIN_RATIONAL",
    "DOMAIN_REAL",
    "DOMAIN_COMPLEX",
]


# autopep8: off
KEY_INT = 0
KEY_FRC = 1
KEY_FLT = 2
KEY_CNS = 3
KEY_VAR = 4
KEY_ADD = 5
KEY_MUL = 6
KEY_POW = 7
KEY_FNC = 8
KEY_LIM = 9
KEY_DER = 10
KEY_ITG = 11
KEY_SET_UNVSL = 12
KEY_SET_EMPTY = 13
KEY_SET_FINIT = 14
KEY_SET_UNION = 15
KEY_SET_INTSC = 16
KEY_SET_DFRNC = 17
KEY_SET_CMPLM = 18
KEY_SET_DOMAIN = 19
KEY_SET_INTVL = 20

CONSTKEY_INF    = 0
CONSTKEY_NEGINF = 1
CONSTKEY_UNDEF  = 2

FUNC_ABS    = 0
FUNC_SIN    = 1
FUNC_COS    = 2
FUNC_TAN    = 3
FUNC_SEC    = 4
FUNC_CSC    = 5
FUNC_COT    = 6
FUNC_ARCSIN = 7
FUNC_ARCCOS = 8
FUNC_ARCTAN = 9
FUNC_ARCSEC = 10
FUNC_ARCCSC = 11
FUNC_ARCCOT = 12
FUNC_LN     = 13
FUNC_LOG    = 14

DOMAIN_NATURAL = 0
DOMAIN_INTEGER = 1
DOMAIN_RATIONAL = 2
DOMAIN_REAL = 3
DOMAIN_COMPLEX = 4
